package tprog04.kremlin.aux_classes;

public enum SseEventType {
    GAME_UPDATE,
    GAME_MESSAGE,
    PRIVATE_MESSAGE,
    GAME_START,
    GAME_END,
    ADVANCE_TURN,
    PHASE_START,
    PHASE_EVENT,
    PHASE_EXECUTED,
    PHASE_END,
    FORCED_PHASE_END,
    ADVANCE_PHASE,
    PLAYER_READY,
    ALL_PLAYERS_READY,
    ACTION_ANNOUNCED,
    ACTION_EXECUTED,
    ACTION_CANCELLED,
    ACTION_FAILED,
    AWAITING_ACTION_ANNOUNCED,
    AWAITING_ACTION_CANCELLED,
    AWAITING_ACTION_RESOLVED,
    AWAITING_ACTION_FAILED,
    TRIAL_BEGIN_VOTING,
    TRIAL_END_VOTING,
    TRIAL_RESOLVED
}
